config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/home/top' => 'home#top'
  get '/home/about' => 'home#about'
  get "/searches/search" => "searches#search", as: 'search' #検索する
  post 'follow/:id' => 'relationships#follow', as:'follow' #フォローする
  get 'users/:id/following' => 'relationships#following',as:'following'
  get 'users/:id/follower' => 'relationships#follower',as: 'follower'
  post 'unfollow/:id' => 'relationships#unfollow', as:'unfollow' #フォローを外す
  root 'home#top'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
  end

  resources :books do
    resources :book_comments,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}

  #ユーザーをフォローする
  def follow(user_id)
      follower.create(followed_id: user_id)
  end

  #ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  #サーチメソッドの定義。if内でさらに検索条件による分岐
  def self.search(search, user_or_book, how_search)
      if how_search == "1"
              User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "2"
              User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "3"
              User.where(['name LIKE ?', "#{search}%"])
      else
              User.where(['name LIKE ?', "%#{search}"])
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, size: "100x100", fallback: "no_image.jpg", class: "center-block" ) %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to following_path(user.id) do %>
				<%= user.following_user.count %>
				<% end %>
			</th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to follower_path(user.id) do %>
				<%= user.follower_user.count %>
				<% end %>
			</th>
		</tr>
		<tr>
			<% if user.id != current_user.id %>
			<td colspan="2">
						<% if current_user.following?(user) %>
        					<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-danger btn-block" %>
      					<% else %>
        					<%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success btn-block" %>
      					<% end %>
      		</td>
			<% end %>
		</tr>
</table>

<%= link_to '',edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>

app/views/users/_searchResults.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>
						<p>フォロー数:<%= user.following_user.count %></p>
					</td>
					<td>
						<p>フォロワー数:<%= user.follower_user.count %></p>
					</td>
					<% if user.id != current_user.id %>
					<td>
							<% if current_user.following?(user) %>
        						<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-danger" %>
      						<% else %>
        						<%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success" %>
      						<% end %>
					</td>
					<% end %>
					<td><%= link_to "Show", user, class: "user_#{user.id} btn btn-default" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
  </div>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class='row'>
	<div class='col-xs-3'>

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class='col-xs-9'>
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>
						<p>フォロー数:<%= user.following_user.count %></p>
					</td>
					<td>
						<p>フォロワー数:<%= user.follower_user.count %></p>
					</td>
					<% if user.id != current_user.id %>
					<td>
							<% if current_user.following?(user) %>
        						<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-danger" %>
      						<% else %>
        						<%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success" %>
      						<% end %>
					</td>
					<% end %>
					<td><%= link_to "Show", user, class: "user_#{user.id} btn btn-default" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
		<!--users一覧 -->

app/views/users/show.html.erb
<div class='row'>
	<div class='col-xs-3'>

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->
		<br>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>
	<div class='col-xs-9'>
		
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="2"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
    							<%= link_to book_favorites_path(book), method: :delete do %>
    							<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% else %>
    							<%= link_to book_favorites_path(book), method: :post do %>
    							<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% end %>
					</td>
					<td>コメント数:<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<!--books一覧 -->