config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/home/top' => 'home#top'
  get '/home/about' => 'home#about'
  get "/searches/search" => "searches#search", as: 'search' #検索する
  post 'follow/:id' => 'relationships#follow', as:'follow' #フォローする
  get 'users/:id/following' => 'relationships#following',as:'following'
  get 'users/:id/follower' => 'relationships#follower',as: 'follower'
  post 'unfollow/:id' => 'relationships#unfollow', as:'unfollow' #フォローを外す
  root 'home#top'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
  end

  resources :books do
    resources :book_comments,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
  end

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments
	has_many :favorites

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	#サーチメソッドの定義。if内でさらに検索条件による分岐
	def self.search(search, user_or_book, how_search)
		  if how_search == "1"
				  Book.where(['title LIKE ?', "#{search}"])
		  elsif how_search == "2"
				  Book.where(['title LIKE ?', "%#{search}%"])
		  elsif how_search == "3"
				  Book.where(['title LIKE ?', "#{search}%"])
		  else
				  Book.where(['title LIKE ?', "%#{search}"])
		  end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_comments = @book.book_comments
    @book_comment = current_user.book_comments.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
    if @book.user == current_user
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
    else #if文で投稿したユーザー以外削除できないようにしている。
      render :index
    end
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<% if book.errors.any? %>
  	<div class="alert alert-warning">
  		<%= pluralize(book.errors.count, 'error') %>
    		<ul>
      			<% book.errors.full_messages.each do |message| %>
        		<li><%= message %></li>
        		<% end %>
            </ul>
    </div>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_searchResults.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="1"></th>
				</tr>
			</thead>

			<tbody>
				<% books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
    							<%= link_to book_favorites_path(book), method: :delete do %>
    							<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% else %>
    							<%= link_to book_favorites_path(book), method: :post do %>
    							<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% end %>
					</td>
					<td><p>コメント数:<%= book.book_comments.count %></p></td>
				</tr>
				<% end %>
			</tbody>
	</table>
  </div>
</div>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %> |
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
		
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="1"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
    							<%= link_to book_favorites_path(book), method: :delete do %>
    							<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% else %>
    							<%= link_to book_favorites_path(book), method: :post do %>
    							<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
    							<%= book.favorites.count %>
    							<% end %>
						<% end %>
					</td>
					<td><p>コメント数:<%= book.book_comments.count %></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to @book.user do %>
						<%= attachment_image_tag @book.user, :profile_image, size:'40x40', fallback: "no-image-mini.jpg" %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td>
						<% if @book.favorited_by?(current_user) %>
    							<%= link_to book_favorites_path(@book), method: :delete do %>
    							<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    							<%= @book.favorites.count %>
    							<% end %>
						<% else %>
    							<%= link_to book_favorites_path(@book), method: :post do %>
    							<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
    							<%= @book.favorites.count %>
    							<% end %>
						<% end %>
					</td>
					<td>
						<p>コメント数:<%= @book.book_comments.count %></p>
					</td>
					<% if @book.user == current_user %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
		</table>
		<table class="table table-hover">
			<tbody>
				<% @book_comments.each do |book_comment| %>
				<tr>
					<td>
					<%= attachment_image_tag(book_comment.user, :profile_image, size:"40x40", fallback: "no-image-mini.jpg") %><br>
					<%= book_comment.user.name %>
					</td>
					<td><%= book_comment.comment %></td>
					<td>
					<% if book_comment.user == current_user %>
						<%= link_to "Destroy",book_book_comment_path(@book.id,book_comment.id),method: :delete,data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book_comment.id}" %>
					</td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
			<% if @book_comment.errors.any? %>
  				<div class="alert alert-warning">
  					<%= pluralize(@book_comment.errors.count, 'error') %>
    				<ul>
      					<% @book_comment.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
        			<% end %>
           			 </ul>
    			</div>
			<% end %>
			<%= form_for @book_comment,url: book_book_comments_path(@book.id) do |f| %>
				<div class="field">
					<div class="col-xs-9">
						<p>comment:</p>
						<%= f.text_area :comment,class: 'form-control', placeholder: "コメントをここに" %>
						<%= f.submit "送信する" %>
					</div>
				</div>
			<% end %>

	</div>
</div>